version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: snapurl-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7-alpine
    container_name: snapurl-redis
    restart: unless-stopped
    ports:
      - "6399:6379"
